spring:
  application:
    name: todo-app-be
  datasource:
    url: jdbc:mysql://localhost:3306/shopdev
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database:  mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        