services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo-app-db
      MYSQL_USER: shintadevuser
      MYSQL_PASSWORD: shintadevpassword
    ports:
      - '3306:3306'
    networks:
      - todo_app
    expose:
      - 3306
    volumes:
      - ./db/mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 1s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: on-failure

  server:
    build: 
      context: ./todo-app-be
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    networks:
      - todo_app
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: shintadevuser
      DB_PASSWORD: shintadevpassword
      DB_NAME: todo-app-db

  frontend:
    build: 
      context: ./todo-app-fe
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    networks:
      - todo_app
    depends_on:
      - server
    expose:
      - 3000
    environment:
      API_HOST: server
    
    
networks:
  todo_app:
    driver: bridge
