services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
  server:
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: mydb
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - server
    environment:
      REACT_APP_SERVER_URL: http://server:8080
networks:
  todo_app:
    driver: bridge
